version: '3'

services:
  backend:
    build: ./backend/
    ports:
      - "5000:5000"
        #tty: true
        #stdin_open: true
        #environment:
        #  - FLASK_ENV=development

  frontend:
    build: ./frontend/
    depends_on:
        - backend
    ports:
        - "7000:7000"
        #- "80:8000"
        #tty: true
        #stdin_open: true
    environment:
      - NODE_ENV=development
      - GATSBY_WEBPACK_PUBLICPATH=/
      - CHOKIDAR_USEPOLLING=1


volumes:
    db_init:
